const GAME_WIDTH = 800;
const GAME_HEIGHT = 400;
const MAX_HP = 100;
const TICK_RATE = 1000 / 60;
const ATTACK_COOLDOWN = 520;
const BLOCK_COOLDOWN = 720;
const MOVE_SPEED = 5.2;
const PLAYER_RADIUS = 28;
const ATTACK_RANGE = 96;
const ATTACK_DAMAGE_BASE = 11;
const COMBO_MULTIPLIER = [1, 1.12, 1.35, 1.65];
const ROUND_WIN = 2;
const ROUND_RESET_DELAY = 2600;

module.exports = {
  GAME_WIDTH,
  GAME_HEIGHT,
  MAX_HP,
  TICK_RATE,
  ATTACK_COOLDOWN,
  BLOCK_COOLDOWN,
  MOVE_SPEED,
  PLAYER_RADIUS,
  ATTACK_RANGE,
  ATTACK_DAMAGE_BASE,
  COMBO_MULTIPLIER,
  ROUND_WIN,
  ROUND_RESET_DELAY,
};
